name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Print PHP version
        run: echo ${{ steps.setup-php.outputs.php-version }}
      - name: chech php syntax
        uses: overtrue/phplint@8.1
        with:
          path:
          options: --exclude=*.log
      - name: Install Copmoser dependencies
        env:
          COMPOSER_AUTH:
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run test
       run: vendor/bin/phpunit

