name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: processcon_dev
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Print PHP version
        run: echo ${{ steps.setup-php.outputs.php-version }}
      - name: chech php syntax
        uses: overtrue/phplint@8.1
        with:
          path:
          options: --exclude=*.log
      - name: Install Copmoser dependencies
        env:
          COMPOSER_AUTH:
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run test
        env:
         DB_HOST: 127.0.0.1
         DB_PORT: ${{ job.services.mysql.ports['3306'] }}
         DB_USERNAME: root
         DB_PASSWORD: null
         DB_DATABASE: processcon_dev

        run: php artisan test
      - name: Install front-end dependencies
        run: |
          npm install
          npm run build
      
      - name: Creat deployement artifact
        run: tar -czf app.gz *
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}
  
          username: ${{ secrets.SSH_USERNAME }}
          script: |
           cd /var/www/

           git checkout -f 

           git pull

      

